### ISSUE TITLE
converter not apply to query args

### ISSUE THREAD

**Issue by pynixwang** [amberframework/granite#383] opened 2020-03-06 11:44 UTC
I have a legacy db use `bigint(20)` to store a uint64 column from java, because of java has no unsigned type. 
```cr
module UInt64Converter
  extend self

  def self.to_db(value) : Granite::Columns::Type
    value ? value.to_i64! : nil
  end

  def self.from_rs(result : ::DB::ResultSet) : UInt64
    result.read(Int64).to_u64!
  end
end

class Block < Granite::Base
  connection mysql
  column id : UInt64, converter: UInt64Converter, primary: true
end

Block.find(14742464276461323789) # not convert to i64
```

**Comment by pynixwang** [comment] 2020-03-06 11:55
Custom converter API should be documented too.

**Comment by crimson-knight** [comment] 2023-04-25 13:53
Duplicate of #451, closing this since it'll be addressed as part of the other issue

**Closed by crimson-knight** 2023-04-25 13:53 UTC
