### ISSUE TITLE
SELECT feature

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#200] opened 2018-05-11 19:54 UTC
add ability to edit SELECT of Query

Is not posible to add custom fields

SELECT *, **categories.name AS category_name** FROM products JOIN categories ON categories.id = products.category_id

like there: **https://apidock.com/rails/v4.0.2/ActiveRecord/QueryMethods/select**

**Comment by noahlh** [comment] 2018-05-19 23:58
This is under discussion @ #184 

Working on it now!

**Comment by robacarp** [comment] 2018-05-23 15:37
Closing as duplicate of #184

**Closed by robacarp** 2018-05-23 15:37 UTC
Labels: kind:feature, status:wip
