### ISSUE TITLE
relations error

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#208] opened 2018-05-15 23:04 UTC
```
instantiating 'Category#subcategories()'
in src/models/category.cr:6: expanding macro

  has_many :subcategories
  ^

in macro 'has_many' /Users/k9/webdev/store_crystal/lib/granite/src/granite/associations.cr:39, line 3:

   1.     def subcategories
   2.
>  3.       Granite::AssociationCollection(self, Subcategorie).new(self)
   4.     end
   5.

undefined constant Subcategorie (did you mean 'Subcategory')
```

**Comment by faustinoaq** [comment] 2018-05-15 23:11
> `undefined constant Subcategorie (did you mean 'Subcategory')`

I think the error is self explanatory :sweat_smile:

**Comment by jaysneg** [comment] 2018-05-15 23:13
1 class Category < Granite::Base
  2   adapter mysql
  3   table_name categories
  4
  5   has_many :products
  6   has_many :subcategories
 12
 13   # id : Int64 primary key is created for you
 14   field name : String
 15   field description : String
 16   field active : Bool
 17   timestamps
 18 end

**Comment by jaysneg** [comment] 2018-05-15 23:13
1 class Subcategory < Granite::Base
  2   adapter mysql
  3   table_name subcategories
  4
  5   belongs_to :category
  6   has_many :products
  7
  8   # id : Int64 primary key is created for you
  9   field name : String
 10   field description : String
 11   field active : Bool
 12   timestamps
 13 end

**Comment by jaysneg** [comment] 2018-05-15 23:15
It appears when i try to get subcategories 

category.subcategories

**Comment by faustinoaq** [comment] 2018-05-15 23:42
> `undefined constant Subcategorie (did you mean 'Subcategory')`

I think you have a typo here, see **Subcategorie**

**Comment by jaysneg** [comment] 2018-05-15 23:44
@faustinoaq 
this method subcategories auto generates by Granite 
[https://github.com/amberframework/granite/blob/master/src/granite/associations.cr#L42](https://github.com/amberframework/granite/blob/master/src/granite/associations.cr#L42)

/Users/k9/webdev/store_crystal/lib/granite/src/granite/associations.cr:39, line 3:

   1.     def subcategories
   2.
>  3.       Granite::AssociationCollection(self, Subcategorie).new(self)
   4.     end

**Comment by faustinoaq** [comment] 2018-05-15 23:47
@jaysneg Oh, my bad, I just realize of that, so I think this is a bug /cc @drujensen

**Comment by jaysneg** [comment] 2018-05-15 23:47
[https://github.com/amberframework/granite/blob/99e2c5bdddd755ddab7047dfd7ca23232e015929/src/granite/associations.cr#L41](https://github.com/amberframework/granite/blob/99e2c5bdddd755ddab7047dfd7ca23232e015929/src/granite/associations.cr#L41)

this line just remove last symbol

**Comment by faustinoaq** [comment] 2018-05-15 23:49
Yeah, we have an similar issue here #129

**Comment by drujensen** [comment] 2018-08-29 19:15
closing as duplicate of #129

**Closed by drujensen** 2018-08-29 19:15 UTC
Labels: kind:bug, status:help-wanted
