### ISSUE TITLE
preload ability

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#207] opened 2018-05-15 10:43 UTC
Add ability to preload data from joined tables and make only one query like includes in Rails ActiveRecord 

https://apidock.com/rails/ActiveRecord/QueryMethods/includes

**Comment by jaysneg** [comment] 2018-05-15 15:07
I think it the same [https://github.com/amberframework/granite/issues/65](https://github.com/amberframework/granite/issues/65)

**Comment by drujensen** [comment] 2018-07-27 12:36
@jaysneg thanks for reporting this.  yes, this is a duplicate of #65.  closing.

**Closed by drujensen** 2018-07-27 12:36 UTC
Labels: status:duplicate
